Repository eslint/csstree, pull requests merged in 2025-04, with the labels that each got.

#22 fix: Remove wrong `scroll-timeline` property patch
  data/patch.json
Labels: bug

#28 fix: Add patch for <cubic-bezier-easing-function>
  data/patch.json
Labels: bug, accepted

#23 fix: Remove `src` descriptor patch
  data/patch.json
  fixtures/definition-syntax/default-properties.json
Labels: bug

#25 fix: Remove `unicode-range` descriptor patch
  data/patch.json
Labels: bug

#30 chore: Remove never used syntaxes
  data/patch.json
Labels: chore

#29 fix: Remove outdated `anchor()` & `anchor-size()` function patch
  data/patch.json
Labels: bug

#32 fix: Update mdn-data and patch
  data/patch.json
  package-lock.json
  package.json
Labels: bug

#34 fix: Types for Node definitions
  lib/index.d.ts
  lib/syntax/node/CDC.js
  lib/syntax/node/CDO.js
  tests/types/types.test.ts
Labels: bug, accepted

#36 feat: Customize tokenizer via the fork API
  lib/__tests/common.js
  lib/generator/create.js
  lib/index.d.ts
  lib/lexer/prepare-tokens.js
  lib/parser/create.js
  lib/syntax/config/mix.js
  lib/syntax/config/parser.js
  lib/syntax/create.js
  lib/utils/get-tokenizer.js
Labels: feature

#38 ci: Update GitHub actions
  .github/workflows/build.yml
  tests/types/types.test.ts
Labels: build
